## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := armv7-android-gcc
ALL_TARGETS += libs
ALL_TARGETS += docs

PREFIX=/usr/local
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8-vp9-nopost-nodocs-armv7-android-v1.3.0-470-g87440ae
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_STRING=v1.3.0-470-g87440ae

VERSION_MAJOR=1
VERSION_MINOR=3
VERSION_PATCH=0

CONFIGURE_ARGS=--target=armv7-android-gcc --disable-examples --sdk-path=/Users/vahagnnikoghosyan/Downloads/android-ndk-r9d
CONFIGURE_ARGS?=--target=armv7-android-gcc --disable-examples --sdk-path=/Users/vahagnnikoghosyan/Downloads/android-ndk-r9d
